server:
  port: 9001

spring:
  spring:
    application:
      name: login-service
  datasource:
    url: jdbc:postgresql://nutrition.postgres.database.azure.com:5432/postgres?user=woo2851&password=tjdals0815!&sslmode=require
    username: woo2851@nutrition.postgres.database.azure.com
    password: tjdals0815!
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    format_sql: true
    use_sql_comments: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

custom:
  api:
    key: DefaultEndpointsProtocol=https;AccountName=woo2851;AccountKey=C2+5QntmqCimJ6qJi8CQOG7uRY5h9W8hqSBvGkiGz0pnEdPgsrKwcFVZUo91Oypa9bwqOfbAti4g+AStzkJkmQ==;EndpointSuffix=core.windows.net