name: Trigger auto deployment for nutrition

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/nutrition-AutoDeployTrigger-e2f3a684-e3ca-4fa6-ab1f-7b75d3bc4016.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.NUTRITION_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NUTRITION_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NUTRITION_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: nutrition.azurecr.io
          registryUsername: ${{ secrets.NUTRITION_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NUTRITION_REGISTRY_PASSWORD }}
          containerAppName: nutrition
          resourceGroup: DefaultResourceGroup-koreacentral
          imageToBuild: nutrition.azurecr.io/nutrition:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


